# HUNTER
HUNTER_MAP = {
    "Hell Ember": "H01",
    "Smiley Face": "H02",
    "Gamekeeper": "H03",
    "The Ripper": "H04",
    "Soul Weaver": "H05",
    "Geisha": "H06",
    "The Feaster": "H07",
    "Wu Chang": "H08",
    "Photographer":"H09",
    "Mad Eyes": "H10",
    "Dream Witches": "H11",
    "Axe Boys": "H12",
    "Evil Reptilian":"H13",
    "Bloody Queen": "H14",
    "Guard 26":"H15",
    "Disciple": "H16",
    "Violinist":"H17",
    "Sculptor": "H18",
    "Undead": "H19",
    "The Breaking Wheel":"H20",
    "Naiad":"H21",
    "Wax Artist":"H22",
    "Nightmare":"H23",
    "Clerk":"H24",
    "Hermit":"H25",
    "Night Watch":"H26",
    "Opera Singer":"H27",
    "Fool's Gold":"H28",
    "The Shadow":"H29",
    "Goatman":"H30",
    "Hullabaloo":"H31"
}
SURVIVOR_MAP= {
    "Lucky Guy": "S01",
    "Doctor": "S02",
    "Lawyer": "S03",
    "Thief": "S04",
    "Gardener": "S05",
    "Magician": "S06",
    "Explorer": "S07",
    "Mercenary": "S08",
    "Coordinator": "S09",
    "Mechanic": "S10",
    "Forward": "S11",
    "The Mind's Eye": "S12",
    "Priestess": "S13",
    "Perfumer": "S14",
    "Cowboy": "S15",
    "Female Dancer": "S16",
    "Seer": "S17",
    "Embalmer": "S18",
    "Prospector": "S19",
    "Enchantress": "S20",
    "Wildling": "S21",
    "Acrobat": "S22",
    "First Officer": "S23",
    "Barmaid": "S24",
    "Postman": "S25",
    "Grave Keeper": "S26",
    "Prisoner": "S27",
    "Entomologist": "S28",
    "Painter": "S29",
    "Batter": "S30",
    "Toy Merchant": "S31",
    "Patient": "S32",
    "Psychologist": "S33",
    "Novelist": "S34",
    "Little girl": "S35",
    "Weeping Clown": "S36",
    "Professor": "S37",
    "Antiquarian": "S38",
    "Composer": "S39",
    "Journalist": "S40",
    "Aeroplanist": "S41",
    "Cheerleader": "S42",
    "Puppeteer": "S43",
    "Fire investigator": "S44",
    "Faro lady": "S45",
    "Knight": "S46",
    "Meteorologist": "S47",
    "Archer": "S48"
}
TRAITS_MAP= {
    "Listen": "T01",
    "Abnormal": "T02",
    "Excitement": "T03",
    "Patroller": "T04",
    "Teleport": "T05",
    "Peeper": "T06",
    "Blink": "T07",
    "Warp": "T08"
}
MAPS = {
    "Arms Factory": "M01",
    "Sacred Heart Hospital": "M02",
    "The Red Church": "M03",
    "Lakeside Village": "M04",
    "Moonlit River Park": "M05",
    "Leo's Memory": "M06",
    "Eversleeping Town": "M07",
    "Golden Cave": "M08",
    "White Sand Street Asylum": "M09",
    "China Town": "M10",
    "Darkwoods": "M11",
    "Kreiburg Racecourse": "M12",
    "Edward's Wish": "M13"
}
maps_cn_en = {
    "军工厂": "Arms Factory",
    "圣心医院": "Sacred Heart Hospital",
    "红教堂": "The Red Church",
    "湖景村": "Lakeside Village",
    "月亮河公园": "Moonlit River Park",
    "里奥的回忆": "Leo's Memory",
    "永眠镇": "Eversleeping Town",
    "闪金石窟": "Golden Cave",
    "白沙街疯人院": "White Sand Street Asylum",
    "唐人街": "China Town",
    "不归林": "Darkwoods",
    "克雷伯格赛马场": "Kreiburg Racecourse",
    "爱德华的心愿": "Edward's Wish"
}
survivor_cn_en = {
    "幸运儿": "Lucky Guy",
    "医生": "Doctor",
    "律师": "Lawyer",
    "慈善家": "Thief",
    "园丁": "Gardener",
    "魔术师": "Magician",
    "冒险家": "Explorer",
    "佣兵": "Mercenary",
    "空军": "Coordinator",
    "机械师": "Mechanic",
    "前锋": "Forward",
    "盲女": "The Mind's Eye",
    "祭司": "Priestess",
    "调香师": "Perfumer",
    "牛仔": "Cowboy",
    "舞女": "Female Dancer",
    "先知": "Seer",
    "入殓师": "Embalmer",
    "勘探员": "Prospector",
    "咒术师": "Enchantress",
    "野人": "Wildling",
    "杂技演员": "Acrobat",
    "大副": "First Officer",
    "调酒师": "Barmaid",
    "邮差": "Postman",
    "守墓人": "Grave Keeper",
    "囚徒": "Prisoner",
    "昆虫学者": "Entomologist",
    "画家": "Painter",
    "击球手": "Batter",
    "玩具商": "Toy Merchant",
    "病患": "Patient",
    "心理学家": "Psychologist",
    "小说家": "Novelist",
    "小女孩": "Little girl",
    "哭泣小丑": "Weeping Clown",
    "教授": "Professor",
    "古董商": "Antiquarian",
    "作曲家": "Composer",
    "记者": "Journalist",
    "飞行家": "Aeroplanist",
    "拉拉队员": "Cheerleader",
    "木偶师": "Puppeteer",
    "火灾调查员": "Fire investigator",
    "法罗女士": "Faro lady",
    "骑士": "Knight",
    "气象学家": "Meteorologist",
    "弓箭手": "Archer"
}
hunter_cn_en = {
    "厂长": "Hell Ember",
    "小丑": "Smiley Face",
    "鹿头": "Gamekeeper",
    "杰克": "The Ripper",
    "蜘蛛": "Soul Weaver",
    "红蝶": "Geisha",
    "黄衣之主": "The Feaster",
    "宿伞之魂": "Wu Chang",
    "摄影师": "Photographer",
    "疯眼": "Mad Eyes",
    "梦之女巫": "Dream Witch",
    "爱哭鬼": "Axe Boy",
    "孽蜥": "Evil Reptilian",
    "红夫人": "Bloody Queen",
    "26号守卫": "Guard 26",
    "使徒": "Disciple",
    "小提琴家": "Violinist",
    "雕刻家": "Sculptor",
    "博士": "Undead",
    "破轮": "The Breaking Wheel",
    "渔女": "Naiad",
    "蜡像师": "Wax Artist",
    "噩梦": "Nightmare",
    "记录员": "Clerk",
    "隐士": "Hermit",
    "守夜人": "Night Watch",
    "歌剧演员": "Opera Singer",
    "愚人金": "Fool's Gold",
    "时空之影": "The Shadow",
    "跛脚羊": "Goatman",
    "喧嚣": "Hullabaloo"
}
